### ISSUE TITLE
Error: Couldn't install: requests 2.0.0

### ISSUE THREAD

**Issue by flamelcanto** [CanaimaGNULinux/buildout.web.canaimagnulinux#30]
Getting required 'gdata==2.0.18'
We have the distribution that satisfies 'gdata==2.0.18'.
Getting required 'collective.geo.mapwidget==2.1.3'
We have the distribution that satisfies 'collective.geo.mapwidget==2.1.3'.
Getting required 'geopy==0.99'
We have the distribution that satisfies 'geopy==0.99'.
Getting required 'requests==2.0.0'
We have no distributions for requests that satisfies 'requests==2.0.0'.
Getting distribution for 'requests==2.0.0'.
Running easy_install:
"/usr/bin/python" "-c" "from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/flamel/.buildout/eggs/tmpJW0p_M" "-v" "/home/flamel/.buildout/downloads/dist/requests-2.0.0.tar.gz"
path=/home/flamel/.buildout/eggs/setuptools-17.0-py2.7.egg

Processing requests-2.0.0.tar.gz
Unpacking requests-2.0.0 to /tmp/easy_install-NE75cH/requests-2.0.0
Unpacking requests-2.0.0/HISTORY.rst to /tmp/easy_install-NE75cH/requests-2.0.0/HISTORY.rst
Unpacking requests-2.0.0/LICENSE to /tmp/easy_install-NE75cH/requests-2.0.0/LICENSE
Unpacking requests-2.0.0/MANIFEST.in to /tmp/easy_install-NE75cH/requests-2.0.0/MANIFEST.in
Unpacking requests-2.0.0/NOTICE to /tmp/easy_install-NE75cH/requests-2.0.0/NOTICE
Unpacking requests-2.0.0/PKG-INFO to /tmp/easy_install-NE75cH/requests-2.0.0/PKG-INFO
Unpacking requests-2.0.0/README.rst to /tmp/easy_install-NE75cH/requests-2.0.0/README.rst
Unpacking requests-2.0.0/requests to /tmp/easy_install-NE75cH/requests-2.0.0/requests
Unpacking requests-2.0.0/requests/__init__.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/__init__.py
Unpacking requests-2.0.0/requests/adapters.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/adapters.py
Unpacking requests-2.0.0/requests/api.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/api.py
Unpacking requests-2.0.0/requests/auth.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/auth.py
Unpacking requests-2.0.0/requests/cacert.pem to /tmp/easy_install-NE75cH/requests-2.0.0/requests/cacert.pem
Unpacking requests-2.0.0/requests/certs.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/certs.py
Unpacking requests-2.0.0/requests/compat.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/compat.py
Unpacking requests-2.0.0/requests/cookies.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/cookies.py
Unpacking requests-2.0.0/requests/exceptions.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/exceptions.py
Unpacking requests-2.0.0/requests/hooks.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/hooks.py
Unpacking requests-2.0.0/requests/models.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/models.py
Unpacking requests-2.0.0/requests/packages to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages
Unpacking requests-2.0.0/requests/packages/__init__.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/__init__.py
Unpacking requests-2.0.0/requests/packages/charade to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade
Unpacking requests-2.0.0/requests/packages/charade/__init__.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/__init__.py
Unpacking requests-2.0.0/requests/packages/charade/big5freq.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/big5freq.py
Unpacking requests-2.0.0/requests/packages/charade/big5prober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/big5prober.py
Unpacking requests-2.0.0/requests/packages/charade/chardistribution.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/chardistribution.py
Unpacking requests-2.0.0/requests/packages/charade/charsetgroupprober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/charsetgroupprober.py
Unpacking requests-2.0.0/requests/packages/charade/charsetprober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/charsetprober.py
Unpacking requests-2.0.0/requests/packages/charade/codingstatemachine.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/codingstatemachine.py
Unpacking requests-2.0.0/requests/packages/charade/compat.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/compat.py
Unpacking requests-2.0.0/requests/packages/charade/constants.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/constants.py
Unpacking requests-2.0.0/requests/packages/charade/cp949prober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/cp949prober.py
Unpacking requests-2.0.0/requests/packages/charade/escprober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/escprober.py
Unpacking requests-2.0.0/requests/packages/charade/escsm.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/escsm.py
Unpacking requests-2.0.0/requests/packages/charade/eucjpprober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/eucjpprober.py
Unpacking requests-2.0.0/requests/packages/charade/euckrfreq.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/euckrfreq.py
Unpacking requests-2.0.0/requests/packages/charade/euckrprober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/euckrprober.py
Unpacking requests-2.0.0/requests/packages/charade/euctwfreq.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/euctwfreq.py
Unpacking requests-2.0.0/requests/packages/charade/euctwprober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/euctwprober.py
Unpacking requests-2.0.0/requests/packages/charade/gb2312freq.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/gb2312freq.py
Unpacking requests-2.0.0/requests/packages/charade/gb2312prober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/gb2312prober.py
Unpacking requests-2.0.0/requests/packages/charade/hebrewprober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/hebrewprober.py
Unpacking requests-2.0.0/requests/packages/charade/jisfreq.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/jisfreq.py
Unpacking requests-2.0.0/requests/packages/charade/jpcntx.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/jpcntx.py
Unpacking requests-2.0.0/requests/packages/charade/langbulgarianmodel.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/langbulgarianmodel.py
Unpacking requests-2.0.0/requests/packages/charade/langcyrillicmodel.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/langcyrillicmodel.py
Unpacking requests-2.0.0/requests/packages/charade/langgreekmodel.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/langgreekmodel.py
Unpacking requests-2.0.0/requests/packages/charade/langhebrewmodel.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/langhebrewmodel.py
Unpacking requests-2.0.0/requests/packages/charade/langhungarianmodel.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/langhungarianmodel.py
Unpacking requests-2.0.0/requests/packages/charade/langthaimodel.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/langthaimodel.py
Unpacking requests-2.0.0/requests/packages/charade/latin1prober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/latin1prober.py
Unpacking requests-2.0.0/requests/packages/charade/mbcharsetprober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/mbcharsetprober.py
Unpacking requests-2.0.0/requests/packages/charade/mbcsgroupprober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/mbcsgroupprober.py
Unpacking requests-2.0.0/requests/packages/charade/mbcssm.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/mbcssm.py
Unpacking requests-2.0.0/requests/packages/charade/sbcharsetprober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/sbcharsetprober.py
Unpacking requests-2.0.0/requests/packages/charade/sbcsgroupprober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/sbcsgroupprober.py
Unpacking requests-2.0.0/requests/packages/charade/sjisprober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/sjisprober.py
Unpacking requests-2.0.0/requests/packages/charade/universaldetector.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/universaldetector.py
Unpacking requests-2.0.0/requests/packages/charade/utf8prober.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/charade/utf8prober.py
Unpacking requests-2.0.0/requests/packages/urllib3 to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3
Unpacking requests-2.0.0/requests/packages/urllib3/__init__.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/__init__.py
Unpacking requests-2.0.0/requests/packages/urllib3/_collections.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/_collections.py
Unpacking requests-2.0.0/requests/packages/urllib3/connectionpool.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/connectionpool.py
Unpacking requests-2.0.0/requests/packages/urllib3/contrib to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/contrib
Unpacking requests-2.0.0/requests/packages/urllib3/contrib/__init__.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/contrib/__init__.py
Unpacking requests-2.0.0/requests/packages/urllib3/contrib/ntlmpool.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/contrib/ntlmpool.py
Unpacking requests-2.0.0/requests/packages/urllib3/contrib/pyopenssl.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/contrib/pyopenssl.py
Unpacking requests-2.0.0/requests/packages/urllib3/exceptions.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/exceptions.py
Unpacking requests-2.0.0/requests/packages/urllib3/fields.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/fields.py
Unpacking requests-2.0.0/requests/packages/urllib3/filepost.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/filepost.py
Unpacking requests-2.0.0/requests/packages/urllib3/packages to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/packages
Unpacking requests-2.0.0/requests/packages/urllib3/packages/__init__.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/packages/__init__.py
Unpacking requests-2.0.0/requests/packages/urllib3/packages/ordered_dict.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/packages/ordered_dict.py
Unpacking requests-2.0.0/requests/packages/urllib3/packages/six.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/packages/six.py
Unpacking requests-2.0.0/requests/packages/urllib3/packages/ssl_match_hostname to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/packages/ssl_match_hostname
Unpacking requests-2.0.0/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py
Unpacking requests-2.0.0/requests/packages/urllib3/poolmanager.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/poolmanager.py
Unpacking requests-2.0.0/requests/packages/urllib3/request.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/request.py
Unpacking requests-2.0.0/requests/packages/urllib3/response.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/response.py
Unpacking requests-2.0.0/requests/packages/urllib3/util.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/util.py
Unpacking requests-2.0.0/requests/sessions.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/sessions.py
Unpacking requests-2.0.0/requests/status_codes.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/status_codes.py
Unpacking requests-2.0.0/requests/structures.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/structures.py
Unpacking requests-2.0.0/requests/utils.py to /tmp/easy_install-NE75cH/requests-2.0.0/requests/utils.py
Unpacking requests-2.0.0/requests.egg-info to /tmp/easy_install-NE75cH/requests-2.0.0/requests.egg-info
Unpacking requests-2.0.0/requests.egg-info/dependency_links.txt to /tmp/easy_install-NE75cH/requests-2.0.0/requests.egg-info/dependency_links.txt
Unpacking requests-2.0.0/requests.egg-info/not-zip-safe to /tmp/easy_install-NE75cH/requests-2.0.0/requests.egg-info/not-zip-safe
Unpacking requests-2.0.0/requests.egg-info/PKG-INFO to /tmp/easy_install-NE75cH/requests-2.0.0/requests.egg-info/PKG-INFO
Unpacking requests-2.0.0/requests.egg-info/SOURCES.txt to /tmp/easy_install-NE75cH/requests-2.0.0/requests.egg-info/SOURCES.txt
Unpacking requests-2.0.0/requests.egg-info/top_level.txt to /tmp/easy_install-NE75cH/requests-2.0.0/requests.egg-info/top_level.txt
Unpacking requests-2.0.0/requirements.txt to /tmp/easy_install-NE75cH/requests-2.0.0/requirements.txt
Unpacking requests-2.0.0/setup.cfg to /tmp/easy_install-NE75cH/requests-2.0.0/setup.cfg
Unpacking requests-2.0.0/setup.py to /tmp/easy_install-NE75cH/requests-2.0.0/setup.py
Unpacking requests-2.0.0/test_requests.py to /tmp/easy_install-NE75cH/requests-2.0.0/test_requests.py
Running requests-2.0.0/setup.py bdist_egg --dist-dir /tmp/easy_install-NE75cH/requests-2.0.0/egg-dist-tmp-hrx7bs
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 1712, in main
    
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 1700, in with_ei_usage
    
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 1716, in <lambda>
    
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 211, in run
    
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 427, in easy_install
    
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 476, in install_item
    
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 655, in install_eggs
    
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 930, in build_and_install
    
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 919, in run_setup
    
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/sandbox.py", line 62, in run_setup
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/sandbox.py", line 105, in run
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/setuptools/sandbox.py", line 64, in <lambda>
  File "setup.py", line 6, in <module>
    except ImportError:
  File "/tmp/easy_install-NE75cH/requests-2.0.0/requests/__init__.py", line 53, in <module>
  File "/tmp/easy_install-NE75cH/requests-2.0.0/requests/packages/urllib3/contrib/pyopenssl.py", line 42, in <module>
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
An error occurred when trying to install requests 2.0.0. Look above this message for any errors that were output by easy_install.
While:
  Installing client1.
  Getting distribution for 'requests==2.0.0'.
Error: Couldn't install: requests 2.0.0

**Comment by flamelcanto** [comment]
error running outside virtualenv.
